### ISSUE TITLE
Undefined variable error.

### ISSUE THREAD

**Issue by simmo9000** [hbroek/reken#20]
**Describe the bug**
Undefined variable error. - LINE 1359

Firefox Error: 

Uncaught (in promise) TypeError: array is undefined
    updateForChildren /reken.js:1359
    controller /reken.js line 1473 > Function:27
    anonymous /reken.js line 1473 > Function:56
    _rekenInit /reken.js:1475
    <anonymous> /reken.js:1528
    promise callback* /reken.js:1523

Chrome Error:

reken.js:1359 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at updateForChildren (reken.js:1359:39)
    at $main.controller (eval at _rekenInit (reken.js:1473:38), <anonymous>:27:5)
    at eval (eval at _rekenInit (reken.js:1473:38), <anonymous>:56:15)
    at _rekenInit (reken.js:1475:17)
    at reken.js:1528:13

** Reken version number ** (see `reken.version`)
Current DIST version.
https://cdn.jsdelivr.net/gh/hbroek/reken/dist/reken.min.js
https://github.com/hbroek/reken/blob/main/src/reken.js

**To Reproduce**
```
<head>
    <script>
        const SERVER = "/json"
        var itemid="1";
        var OPTIONS = {credentials: 'include'};
        var reply = {};
        var V, I = {};
        function updateReply() {
            if(isObject(reply))
                I = Object.values(reply)[0] || {};
            if(isObject(I.vars))
                V = Object.values(I.vars) || {};
        }
        function isObject(variable) {
            return variable !== null && typeof variable === 'object';
        }
    </script>
</head>
<body>
    <div data-rest="reply:${SERVER}/?id=${itemid}" data-rest-options="OPTIONS" data-calc="updateReply()"></div>
    <label>Item ID<input placeholder="Item ID" data-value="itemid" type="text" /></label>
    <table>
    <thead>
        <th>#</th>
        <th>Name</th>
        <th>Email</th>
    </thead>
    <tbody>
    <tr>
        <td data-text="${I.label}"></td>
    </tr>
    </tbody>
    </table>
<table>
<tbody data-for="v:V">
<tr>
<td data-text="${v.item.name}"></td>
<td data-text="${v.item.value}"></td>
</tr>
</tbody>
</table>
<script src="https://cdn.jsdelivr.net/gh/hbroek/reken/dist/reken.min.js"></script> 
</body>
```

**Desktop (please complete the following information):**
Linux 5.15.141
Firefox 113.0.2
and Chrome latest.

**Additional context**
Line 1359 of reken.js - 
Looks like array.length is being used without checking if array exists.
It may be because in the HTML above, the for loop `<tbody data-for="v:V">` , V does not have a value until the JSON reply is received.

Great concise little framework BTW!  Well done.

**Comment by hbroek** [comment]
Fixed with commit https://github.com/hbroek/reken/commit/5bdf2dcd904b648a9cae4bd28fba2163d7e02670
