### ISSUE TITLE
Reken Developer Handbook as printed book

### ISSUE THREAD

**Issue by unuseless** [hbroek/reken#24]
Non-kindle reader here.
Have you thought of publishing the Reken Developer Handbook as printed book?  It should be simple from the amazon kdp website.

**Comment by hbroek** [comment]
@unuseless thanks for the suggestion. I have looked into that. I was actually working on creating the printed book via aamazon kdp and ordered some proofprints. Unfortunately all the source formatting was very cluttered looking and required a lot of additional manual work. If there is enough demand, I would consider oublishing the Reken Developer Handbook as a printed book.

I also found the cost price via Amazon publishig was a minimum of $19.95 and with some markup to support Reken would be close to 30 dollars, which would make the book pretty expensive. Would that be something you would be willing to pay?

I found using the kindle app on my tablet to be  close resemblances of a hardcopy book, would that be something that would work for you?

Best
Henry

**Comment by unuseless** [comment]
Thanks @hbroek .
I was considering buying as a form of support for the project, not to make more work for you.  However I do not have access to a kindle app or reader.
Can you "sell a pdf" through e.g. https://tentary.com/ ? You could charge more than kindle.

**Comment by hbroek** [comment]
Hi,

Thanks for the suggestion. I made a PDF with table of contents available on https://reken.tentary.com/p/0KlwE5

Best
Henry

**Comment by unuseless** [comment]
Thanks, it worked!
